### PR TITLE
Fix issue 214

### LINKED ISSUE #214: Deployed contract promise doesn't resolve.
Commit: 5648247ae8a64d3c7c1a3ffbb9d3f7884ec7e06e
Location: https://github.com/magmo/rps-poc/blob/ag-challenge/src/wallet/redux/sagas/blockchain.ts#L40

Our app is (upredictably) victim to [this bug](https://github.com/trufflesuite/truffle-contract/issues/70#issuecomment-355376332), the obvious symptom being:
- upon successfully deploying the contract, the promise returned by `simpleAdjudicatorContract.new` does not resolve.
- since `call` blocks until that promise resolves, player B's wallet never gets the adjudicator's address, and thus Player A's does not as well
- consequently, both players' games are locked in a "waiting to deploy state"

### PR DESCRIPTION
**Pull request by andrewgordstewart**
Closes #214

### CODE REVIEW

File: src/contracts/SimpleAdjudicator.ts [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+
+import connectedWeb3 from '../wallet/web3';
+
+export async function deploySimpleAdjudicator(channelId: string, amount: BN) {
+  const truffleContract = await setupContract();
+
+  let contractBytecode;
+  contractBytecode = truffleContract.bytecode;
+
+  Object.keys(truffleContract.links).forEach(linkName => {
```
Comment (lalexgap) [inline src/contracts/SimpleAdjudicator.ts]:
```suggestion
 // Manually link contracts into the byteCode so we can use web3 to deploy the bytecode
// This avoids an issue with truffleContract.new not always resolving.
 Object.keys(truffleContract.links).forEach(linkName => {
```

File: src/contracts/SimpleAdjudicator.ts [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+
+import connectedWeb3 from '../wallet/web3';
+
+export async function deploySimpleAdjudicator({ channelId, amount }: { channelId: string, amount: BN }) {
+  const truffleContract = await setupContract();
+
+  let contractBytecode;
+  contractBytecode = truffleContract.bytecode;
+
+  Object.keys(truffleContract.links).forEach(linkName => {
```
Comment (kerzhner) [inline src/contracts/SimpleAdjudicator.ts]: @andrewgordstewart Maybe leave a comment on why these manipulations are necessary.

File: src/contracts/SimpleAdjudicator.ts [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+  });
+
+  const web3Contract = new connectedWeb3.eth.Contract(simpleAdjudicatorArtifact.abi, connectedWeb3.eth.defaultAccount);
+
+  const tx = web3Contract.deploy({
+    data: contractBytecode,
+    arguments: [channelId],
+  });
+
+  const deployedContract = await tx.send({ from: connectedWeb3.eth.defaultAccount, value: amount.toString() });
```
Comment (kerzhner) [inline src/contracts/SimpleAdjudicator.ts]: @andrewgordstewart Elsewhere in the app, we use the `yield` + the saga framework to block on asynchronous calls. Do you see us using the `await` pattern in other parts of the app going forward?

File: src/contracts/SimpleAdjudicator.ts [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
```
Comment (kerzhner) [inline src/contracts/SimpleAdjudicator.ts]: @andrewgordstewart Elsewhere in the app, we use the `yield` + the saga framework to block on asynchronous calls. Do you see us using the `await` pattern in other parts of the app going forward?

Comment (andrewgordstewart) [reply src/contracts/SimpleAdjudicator.ts]: I think this would improve testability, along with @tomclose's work on moving more logic into reducers.

Since reducers are synchronous, you couldn't move this logic into a reducer, for instance.

However, by moving this logic out of a saga, we could more easily write unit tests for, eg., `deployContract`.

So, I think we should explore this idea: extracting some async logic out of sagas, and using the (more common) `await` pattern.
